import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                const key = "ai4smb_anon_id";
                let id = localStorage.getItem(key);
                if (!id) {
                  id = crypto.randomUUID();
                  localStorage.setItem(key, id);
                }
                fetch("/api/event", {
                  method: "POST",
                  headers: { "Content-Type": "application/json" },
                  body: JSON.stringify({
                    anonId: id,
                    event: "pageview",
                    path: window.location.pathname
                  })
                }).catch(() => {});
              })();
            `,
          }}
        />
        {children}
      </body>
    </html>
  );
}
